[package]
name = "jpegdec_sys"
version = "0.1.0"
authors = ["9names <60134748+9names@users.noreply.github.com>"]
edition = "2018"
links = "jpegdec"

[dependencies]
cty = "*"

[build-dependencies]
bindgen = "^0"
cc = "^1"
